version: '3.8'
services:
  redis:
    image: redis:7.0.15
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bitcoind:
    image: cryptodockerhub/bitcoin-core:26.0 # https://github.com/crypto-docker/bitcoin-core
    container_name: bitcoind
    network_mode: host # bridge doesnt seem to work
    ports:
    - 8332:8332
    - 18332:18332
    - 18443:18443
    - 8333:8333
    - 18333:18333
    - 18444:18444

    volumes:
      - ./docker/bitcoind/config.conf:/data/config.conf
      - ./docker/bitcoind/regtest:/home/coinuser/.bitcoin/regtest/
      - bitcoind-data:/data

volumes:
  bitcoind-data:
  redis-data:
  postgres-data:
