version: '3.8'
services:
  redis:
    image: redis:7.0.15
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
